### ISSUE TITLE
The Bot Does Not Work Right

### ISSUE THREAD

**Issue by ItsRandy** [Itz-Hyperz/RandyBigSmellyBot#5]
I Am ItzRandy and try to use the bot to ban that fake randy and nothing happens if you could help me that would be nice

**Comment by Itz-Hyperz** [comment]
It bans by account ID, meaning if you are owner, and its your account ID being banned, it wont be able to ban you, as no one is higher than the owner in a server. Otherwise you need Hyperz Basic Bot. Which can be found here: https://hyperz.dev/shop

If you are still having trouble, talk to the person who is in charge of all future changes and commits (Caleb W.)

Thanks for reaching out, hopefully this solves your problem 😄
